# Server
server.port=5000
spring.application.name=sm-karupatti-backend

# MySQL DataSource
spring.datasource.url=jdbc:postgresql://dpg-d8pdua3tqb8s7383dmfg-a.oregon-postgres.render.com:5432/sm_karupatti
spring.datasource.username=smkarupatti
spring.datasource.password=cO7TvBNyzvXlpGesmO1DJw5EpuHlt1jM
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=sm_karupatti_super_secret_jwt_key_2024_java_spring_boot_edition
app.jwt.expiration-ms=2592000000

# Cloudinary
cloudinary.cloud-name=placeholder_cloud_name
cloudinary.api-key=placeholder_api_key
cloudinary.api-secret=placeholder_api_secret

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER:placeholder@gmail.com}
spring.mail.password=${EMAIL_PASS:placeholder_app_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App
app.admin.email=smkarupattishop@gmail.com
app.client.url=http://localhost:5173


# File Upload limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.smkarupatti=INFO
logging.level.org.springframework.security=WARN
